name: Docker push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}

      - name: Install Docker Compose
        run: sudo apt -y update && sudo apt -y install docker-compose

      - name: Docker Build
        run: docker-compose build

      - name: Docker Push
        run: docker push tmvdl/ollama -a
